### ISSUE TITLE
버그 수정 및 제대로 된 i18n 지원 요청

### ISSUE THREAD

**Issue by pseol2190** [2DU/MediaWiki-Skin-Acme#21]
- [Special:Version](http://pseol.urown.cloud:82/plavormindtest/index.php?title=Special:Version&useskin=Acme) 문서를 보면 Acme 스킨의 이름, 버전, 라이선스가 제대로 표시되지 않습니다. ~퍼블릭 도메인?~
- 메뉴 이름에 i18n을 적용하여 다국어가 지원되도록 해 주시기 바랍니다.
- 도구 메뉴에 있는 '작성 필요([[특수:필요한문서]])', '짧은 문서([[특수:짧은문서]])', '파일 올리기([[특수:파일올리기]])', '역링크([[특수:가리키는문서]])' 및 '특수 문서([[Special:특수문서]])' 버튼을 누를 시 전부 [이와 같이](http://pseol.urown.cloud:82/plavormindtest/index.php?title=Special:필요한문서&useskin=acme) 특수 문서가 없다는 메시지가 표시됩니다.
- 사용자 메뉴에 있는 '로그아웃([[특수:로그아웃]])' 버튼에서도 같은 현상이 발생합니다.
- MediaWiki: 이름공간 내의 문서를 통해 상단 메뉴를 자유롭게 변경(customize)할 수 있도록 해 주시기 바랍니다.

**Comment by Hoto-Cocoa** [comment]
라이센스가 표기되지 않는다고 해서 PD인게 아닙니다.

**Comment by pseol2190** [comment]
~FREE LICENSE라고 적혀 있길래 그냥 해본 말이었습니다.~

**Comment by Git0xf** [comment]
이슈 트래커에도 아무 말이나 막 뱉으시는 게 습관이신가요? 습관이시면 고치세요.

**Comment by pseol2190** [comment]
당신들이야말로 유독 저한테만 계속 참견하는 게 습관이신가요? [너](https://uncyclopedia.kr/wiki/틀:너)가 뭐라고 하던지 [신경 쓰지](https://en.wikipedia.org/wiki/Wikipedia:Revert,_block,_ignore) [않습니다](http://pseol.urown.cloud:81/exit/User:PlavorSeol/GitHub_block_log). 해당 요청 각하하며, 그럴 생각 전혀 없습니다.

**Comment by yeoncomi** [comment]
@pseol2190 도대체 백괴사전 링크는 왜 있는거죠 백괴사전 판리자로서 불편한데스

**Comment by Hoto-Cocoa** [comment]
업데이트 받기 싫으신가보죠?

**Comment by 2DU** [comment]
더 싸우면 블락합니다 더 글 쓰지 마세요

**Comment by Hoto-Cocoa** [comment]
"너"라고 하는걸 보니 당신이 저희보다 우월하거나 높은 직급의 사람인걸로 생각하는 것 같은데 지금은 저희가 갑이고 당신이 을입니다.

**Comment by Hoto-Cocoa** [comment]
깃허브에서 갑을 따져서 뭐하나 싶지만요.

**Comment by 2DU** [comment]
암튼 더 글 쓰지 마십셔 최후 통봅니다

**Comment by pseol2190** [comment]
그러면 안 쓸 줄 알았나?

**Comment by 2DU** [comment]
@pseol2190 너 차단

**Comment by Hoto-Cocoa** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋ 깃허브에선 레포 주인이 최고인 것을 모르는

**Comment by Tenpower** [comment]
대체 기각과 각하가 왜 나오냐? 여기가 위키냐?
